name: CD

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  push_to_registries:
    name: 发布多平台docker镜像
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 登录docker
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 登录github仓库
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: 推送标记
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: |
            brinishness/go-test
            ghcr.io/${{ github.repository }}

      - name: 配置buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          use: true
          platforms: linux/amd64,linux/arm64,linux/arm64/v8,linux/arm/v7

      - name: 构建并发布镜像
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          no-cache: true
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}